version: 2
updates:

  - package-ecosystem: npm
    schedule:
      interval: daily
    directory: /
    open-pull-requests-limit: 20
        ignore:
        - dependency-name: eslint
          versions: "> 8"