name: Test and Notify Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test-and-notify:
    runs-on: ubuntu-latest

    steps:
      # Checkout with deploy key for the main repo
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

     
      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: latest

      - name: Install Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install Dependencies
        run: pnpm install

      - name: Run Tests
        id: tests
        run: echo "hi"
        continue-on-error: true

      - name: Handle Notification
        if: steps.tests.outcome == 'failure' || steps.prettier.outcome == 'failure'
        run: |
          cd /tmp
          git clone http://192.168.0.35:3000/brrock/gitemailthinggamex.git
          cd gitemailthinggamex
          bun install
          if [[ "${{ steps.tests.outcome }}" == "failure" then
            bun run sendfailed
          else
            bun run sendsuccess
          fi
