name: Test and Notify Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test-and-notify:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ssh-key: ${{ secrets.SSH_PRIVATE_KEY }}
          
      - name: Setup SSH for Git server
        uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
          
      - name: Add Git server to known hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H 192.168.0.35 >> ~/.ssh/known_hosts
          
      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: latest
          
      - name: Install Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest
          
      - name: Install Dependencies
        run: pnpm install
        
      - name: Run Tests
        id: tests
        run: pnpm test
        continue-on-error: true
        
      - name: Run Prettier
        id: prettier
        run: pnpm prettier
        continue-on-error: true
        
      - name: Commit Prettier Changes
        if: steps.prettier.outcome == 'success'
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add .
          git diff --staged --quiet || git commit -m "style: apply prettier formatting"
          git push
          
      - name: Handle Notification
        if: steps.tests.outcome == 'failure' || steps.prettier.outcome == 'failure'
        run: |
          cd /tmp
          # Using SSH URL
          git clone git@192.168.0.35:brrock/gitemailthinggamex.git
          cd gitemailthinggamex
          bun install
          if [[ "${{ steps.tests.outcome }}" == "failure" || "${{ steps.prettier.outcome }}" == "failure" ]]; then
            bun run sendfailed
          else
            bun run sendsuccess
          fi