name: Update Dependencies

on:
  schedule:
    - cron: '0 12 */2 * *' # Runs every other day at 12:00 UTC
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  update-dependencies:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js (LTS)
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install npm-check-updates
        run: npm install -g npm-check-updates

      - name: Run npm-check-updates and Extract Updated Packages
        id: run-ncu
        run: |
          ncu -u -x eslint > ncu.log
          cat ncu.log
          
          # Extract updated packages and their versions
          UPDATED_PACKAGES=$(grep -E '^\s*[^ ]+\s+\S+\s+→\s+\S+' ncu.log | sed 's/^ *//' | tr '\n' ', ' | sed 's/, $//')
          
          echo "UPDATED_PACKAGES=$UPDATED_PACKAGES" >> $GITHUB_ENV

      - name: Install updated dependencies
        id: install-dependencies
        run: |
          npm install > npm-install.log 2>&1 || echo "INSTALL_FAILED=true" >> $GITHUB_ENV
        continue-on-error: true

      - name: Check for changes and Commit
        if: success() && env.INSTALL_FAILED != 'true'
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          
          git add package.json package-lock.json
          
          if git diff --cached --quiet; then
            echo "No changes to commit."
            exit 0
          else
            COMMIT_MESSAGE="deps: update dependencies"
            echo "Committing with message: $COMMIT_MESSAGE"
            git commit -m "$COMMIT_MESSAGE" -m "${{ env.UPDATED_PACKAGES }}"
            git push
          fi

      - name: Create GitHub Issue if npm install fails
        if: env.INSTALL_FAILED == 'true'
        run: |
          ISSUE_BODY=$(cat <<-END
          ## Dependency Update Failed

          The automated dependency update process encountered an error during the npm install step.

          ### npm-check-updates logs:
          \`\`\`
          $(cat ncu.log)
          \`\`\`

          ### npm install logs:
          \`\`\`
          $(cat npm-install.log)
          \`\`\`

          Please review the logs and take appropriate action to resolve the issue.
          END
          )
          gh issue create --repo ${{ github.repository }} --title "Dependency Update Failed: npm install error" --body "$ISSUE_BODY"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}